services:
  node-linux-builder:
    container_name: node-linux-builder
    build: .
    # run yarn install, yarn test, and yarn build with sh -c
    command: >
      sh -c "yarn"
    # volumes:
      # - ./bin/:/usr/src/app/bin/
